baseURL = 'https://example.org/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = 'Garnet Docs'
    languageCode = 'en'
    languageName = 'English'
    weight = 1
  [languages.ru]
    title = 'Garnet Документация'
    languageCode = 'ru'
    languageName = 'Русский'
    weight = 2

[module]
  [[module.imports]]
    path = 'github.com/vskhoroshev/v0-stamp-hugo-theme'
